import type { PortfolioData, PortfolioProjectRow } from "@/lib/portfolio/types";

const projects: PortfolioProjectRow[] = [
  {
    id: "00000000-0000-0000-0000-0000000000e1",
    code: "EPU",
    name: "Triển khai PMT-EMS",
    organizationName: "Trường Đại học Điện lực",
    status: "active",
    contractValue: 1450000000,
    startDate: "2026-07-01",
    dueDate: "2026-10-15",
    health: "at_risk",
    totalIssues: 128,
    openIssues: 34,
    overdueIssues: 6,
    modules: 42,
    stages: 5,
    stageProgress: 62,
    milestones: 9,
    overdueMilestones: 1,
    tasks: 36,
    blockedTasks: 2,
    overdueTasks: 4,
    openReminders: 7,
    overdueReminders: 2,
    alertScore: 15,
    nextDueDate: "2026-09-11",
  },
  {
    id: "00000000-0000-0000-0000-0000000000h1",
    code: "HIUCR",
    name: "Web/Mobile Release",
    organizationName: "HIU",
    status: "active",
    contractValue: 680000000,
    startDate: "2026-08-01",
    dueDate: "2026-09-30",
    health: "late",
    totalIssues: 74,
    openIssues: 21,
    overdueIssues: 5,
    modules: 18,
    stages: 4,
    stageProgress: 70,
    milestones: 6,
    overdueMilestones: 1,
    tasks: 22,
    blockedTasks: 1,
    overdueTasks: 3,
    openReminders: 5,
    overdueReminders: 1,
    alertScore: 11,
    nextDueDate: "2026-09-16",
  },
];

export function createDemoPortfolio(): PortfolioData {
  return {
    source: "demo",
    generatedAt: new Date().toISOString(),
    projects,
    summary: {
      projectCount: projects.length,
      activeProjects: projects.filter((project) => project.status === "active").length,
      atRiskProjects: projects.filter((project) => project.health === "at_risk").length,
      lateProjects: projects.filter((project) => project.health === "late").length,
      totalIssues: projects.reduce((total, project) => total + project.totalIssues, 0),
      openIssues: projects.reduce((total, project) => total + project.openIssues, 0),
      overdueIssues: projects.reduce((total, project) => total + project.overdueIssues, 0),
      openReminders: projects.reduce((total, project) => total + project.openReminders, 0),
      overdueReminders: projects.reduce((total, project) => total + project.overdueReminders, 0),
      totalContractValue: projects.reduce((total, project) => total + (project.contractValue ?? 0), 0),
    },
  };
}
