import { addScheduleDuration, countScheduleDays, nextScheduleDate, normalizeScheduleStart } from "@/lib/planning/schedule";
import type { AutoGeneratePlanInput, AutoGeneratePlanPreview, AutoGeneratedStage, AutoPlanProfile } from "@/lib/planning/types";

const profiles: Record<AutoPlanProfile, Array<Omit<AutoGeneratedStage, "code" | "durationDays" | "startDate" | "endDate" | "sortOrder"> & { ratio: number }>> = {
  standard_implementation: [
    { ratio: 8, name: "Khởi động & lập kế hoạch", description: "Chốt phạm vi, vai trò, nguyên tắc phối hợp và baseline kế hoạch triển khai.", color: "#22D3EE", milestoneTitle: "Baseline kế hoạch được duyệt", milestoneDescription: "Master Plan, phạm vi và cơ chế điều hành được các bên xác nhận." },
    { ratio: 18, name: "Khảo sát & phân tích nghiệp vụ", description: "Làm rõ hiện trạng, yêu cầu nghiệp vụ, dữ liệu nguồn và tiêu chí nghiệm thu.", color: "#8B5CF6", milestoneTitle: "Tài liệu phân tích được xác nhận", milestoneDescription: "Yêu cầu nghiệp vụ, dữ liệu và phạm vi triển khai đủ điều kiện bước sang cấu hình." },
    { ratio: 30, name: "Cấu hình & phát triển", description: "Thực hiện cấu hình hệ thống, phát triển bổ sung và tích hợp theo phạm vi đã duyệt.", color: "#3B82F6", milestoneTitle: "Hoàn tất cấu hình/phát triển chính", milestoneDescription: "Các hạng mục trọng yếu sẵn sàng cho kiểm thử nội bộ và UAT." },
    { ratio: 18, name: "Kiểm thử nội bộ & UAT", description: "Kiểm thử chức năng, rà soát lỗi, xác nhận luồng nghiệp vụ với người dùng chính.", color: "#F59E0B", milestoneTitle: "UAT đạt điều kiện nghiệm thu", milestoneDescription: "Các lỗi quan trọng được xử lý hoặc có phương án kiểm soát trước chuyển giao." },
    { ratio: 14, name: "Đào tạo & chuyển giao", description: "Đào tạo người dùng, bàn giao tài liệu vận hành và chuẩn bị dữ liệu/cấu hình go-live.", color: "#10B981", milestoneTitle: "Hoàn tất đào tạo và bàn giao", milestoneDescription: "Người dùng chính có đủ tài liệu, quyền truy cập và hướng dẫn vận hành." },
    { ratio: 12, name: "Nghiệm thu & Go-live", description: "Chốt nghiệm thu, triển khai chính thức, theo dõi sau go-live và đóng các tồn đọng cuối.", color: "#F43F5E", milestoneTitle: "Go-live và nghiệm thu dự án", milestoneDescription: "Hệ thống vận hành chính thức và có biên bản nghiệm thu/đóng giai đoạn." },
  ],
  compressed_delivery: [
    { ratio: 12, name: "Kickoff nhanh", description: "Xác nhận phạm vi tối thiểu, lịch triển khai và đầu mối quyết định.", color: "#22D3EE", milestoneTitle: "Scope triển khai nhanh được chốt", milestoneDescription: "Phạm vi, timeline và trách nhiệm đã đủ rõ để chạy dự án tốc độ cao." },
    { ratio: 20, name: "Fit-gap & thiết kế giải pháp", description: "Rà soát yêu cầu, xác định gap quan trọng và phương án triển khai tinh gọn.", color: "#8B5CF6", milestoneTitle: "Fit-gap được duyệt", milestoneDescription: "Các gap/rủi ro trọng yếu được thống nhất hướng xử lý." },
    { ratio: 34, name: "Build & tích hợp", description: "Cấu hình, phát triển và tích hợp theo danh sách ưu tiên đã chốt.", color: "#3B82F6", milestoneTitle: "Build sẵn sàng UAT", milestoneDescription: "Build chính đã đủ điều kiện chuyển sang kiểm thử người dùng." },
    { ratio: 22, name: "UAT & sửa lỗi ưu tiên", description: "Kiểm thử người dùng, xử lý blocker và khóa danh sách lỗi sau UAT.", color: "#F59E0B", milestoneTitle: "UAT khóa lỗi trọng yếu", milestoneDescription: "Blocker được xử lý hoặc có phương án chấp nhận rủi ro." },
    { ratio: 12, name: "Cutover & Go-live", description: "Chuẩn bị cutover, đào tạo nhanh, go-live và hỗ trợ sau triển khai.", color: "#10B981", milestoneTitle: "Go-live hoàn tất", milestoneDescription: "Dự án lên production và chuyển sang vận hành ổn định." },
  ],
  uat_go_live: [
    { ratio: 10, name: "Readiness & kế hoạch UAT", description: "Rà soát điều kiện kiểm thử, dữ liệu mẫu, user key và tiêu chí nghiệm thu.", color: "#22D3EE", milestoneTitle: "UAT readiness được xác nhận", milestoneDescription: "Môi trường, dữ liệu và kịch bản UAT đã sẵn sàng." },
    { ratio: 16, name: "Hoàn thiện cấu hình", description: "Đóng các cấu hình còn thiếu và xử lý tồn đọng trước UAT.", color: "#8B5CF6", milestoneTitle: "Cấu hình sẵn sàng kiểm thử", milestoneDescription: "Các cấu hình cần thiết đã hoàn tất cho phạm vi UAT." },
    { ratio: 32, name: "UAT vòng chính", description: "Người dùng thực hiện kịch bản kiểm thử, ghi nhận lỗi và xác nhận kết quả.", color: "#F59E0B", milestoneTitle: "UAT vòng chính hoàn tất", milestoneDescription: "Kịch bản trọng yếu được chạy xong và có danh sách kết quả." },
    { ratio: 24, name: "Fix, retest & sign-off", description: "Sửa lỗi, kiểm thử lại, thống nhất danh sách ngoại lệ và sign-off.", color: "#3B82F6", milestoneTitle: "UAT sign-off", milestoneDescription: "Các bên xác nhận đủ điều kiện chuyển sang go-live." },
    { ratio: 18, name: "Go-live & hypercare", description: "Chạy chuyển đổi, theo dõi vận hành đầu kỳ và xử lý hỗ trợ sau go-live.", color: "#10B981", milestoneTitle: "Go-live ổn định", milestoneDescription: "Hệ thống vận hành ổn định trong giai đoạn hỗ trợ đầu tiên." },
  ],
};

function allocateDurations(totalDays: number, ratios: number[]) {
  const base = ratios.map((ratio) => Math.max(1, Math.floor((totalDays * ratio) / ratios.reduce((sum, item) => sum + item, 0))));
  let delta = totalDays - base.reduce((sum, item) => sum + item, 0);
  const order = ratios
    .map((ratio, index) => ({ index, fraction: ((totalDays * ratio) / ratios.reduce((sum, item) => sum + item, 0)) % 1 }))
    .sort((a, b) => b.fraction - a.fraction);
  let cursor = 0;
  while (delta > 0) {
    base[order[cursor % order.length].index] += 1;
    delta -= 1;
    cursor += 1;
  }
  while (delta < 0) {
    const target = [...base.keys()].sort((a, b) => base[b] - base[a])[0];
    if (base[target] <= 1) break;
    base[target] -= 1;
    delta += 1;
  }
  return base;
}

function compactStages(profile: AutoPlanProfile, totalDays: number) {
  const source = profiles[profile];
  if (totalDays >= source.length) return source;
  return source.slice(0, Math.max(1, totalDays)).map((stage, index, selected) => {
    if (index !== selected.length - 1) return stage;
    return { ...stage, name: `${stage.name} / Go-live`, milestoneTitle: "Hoàn tất kế hoạch tự động", milestoneDescription: "Các mốc chính trong khung thời gian ngắn đã được hoàn tất." };
  });
}

export function createAutoPlanPreview(input: Pick<AutoGeneratePlanInput, "startDate" | "targetEndDate" | "scheduleMode" | "profile">): AutoGeneratePlanPreview {
  const normalizedStart = normalizeScheduleStart(input.startDate, input.scheduleMode);
  const totalDays = countScheduleDays(normalizedStart, input.targetEndDate, input.scheduleMode);
  const template = compactStages(input.profile, totalDays);
  const durations = allocateDurations(Math.max(1, totalDays), template.map((stage) => stage.ratio));
  let cursor = normalizedStart;
  const stages = template.map((stage, index) => {
    const isLast = index === template.length - 1;
    const endDate = isLast ? input.targetEndDate : addScheduleDuration(cursor, durations[index], input.scheduleMode);
    const durationDays = Math.max(1, countScheduleDays(cursor, endDate, input.scheduleMode));
    const generated: AutoGeneratedStage = {
      code: `STAGE-${String(index + 1).padStart(2, "0")}`,
      name: stage.name,
      description: stage.description,
      durationDays,
      startDate: cursor,
      endDate,
      color: stage.color,
      sortOrder: (index + 1) * 10,
      milestoneTitle: stage.milestoneTitle,
      milestoneDescription: stage.milestoneDescription,
    };
    cursor = nextScheduleDate(endDate, input.scheduleMode);
    return generated;
  });
  return { totalDays, stageCount: stages.length, milestoneCount: stages.length, stages };
}
