import type { ContractData, ContractDetailItem, ContractOverviewItem } from "@/lib/contract/types";

const overview: ContractOverviewItem[] = [
  {
    id: "demo-subsystem-1",
    parentId: null,
    code: "I",
    name: "Đào tạo & Quản lý học tập",
    itemType: "subsystem",
    ownerDepartmentId: null,
    ownerDepartmentName: "Phòng Đào tạo",
    moduleStatusCode: null,
    moduleStatusLabel: null,
    classification: null,
    sortOrder: 1,
    issueTotal: 46,
    handedOver: 35,
    remaining: 11,
    progress: 76,
    detailCount: 14,
  },
  {
    id: "demo-module-1",
    parentId: "demo-subsystem-1",
    code: "1.1",
    name: "Đăng ký học phần",
    itemType: "module",
    ownerDepartmentId: "demo-dept-1",
    ownerDepartmentName: "Phòng Đào tạo",
    moduleStatusCode: "ready_training",
    moduleStatusLabel: "Sẵn sàng tập huấn",
    classification: "Core",
    sortOrder: 2,
    issueTotal: 28,
    handedOver: 21,
    remaining: 7,
    progress: 75,
    detailCount: 8,
  },
  {
    id: "demo-module-2",
    parentId: "demo-subsystem-1",
    code: "1.2",
    name: "Quản lý chương trình đào tạo",
    itemType: "module",
    ownerDepartmentId: "demo-dept-1",
    ownerDepartmentName: "Phòng Đào tạo",
    moduleStatusCode: "surveyed",
    moduleStatusLabel: "Đã khảo sát",
    classification: "Core",
    sortOrder: 3,
    issueTotal: 18,
    handedOver: 14,
    remaining: 4,
    progress: 78,
    detailCount: 6,
  },
  {
    id: "demo-subsystem-2",
    parentId: null,
    code: "II",
    name: "Tài chính & Học phí",
    itemType: "subsystem",
    ownerDepartmentId: null,
    ownerDepartmentName: "Phòng Tài chính",
    moduleStatusCode: null,
    moduleStatusLabel: null,
    classification: null,
    sortOrder: 4,
    issueTotal: 19,
    handedOver: 11,
    remaining: 8,
    progress: 58,
    detailCount: 5,
  },
  {
    id: "demo-module-3",
    parentId: "demo-subsystem-2",
    code: "2.1",
    name: "Quản lý học phí",
    itemType: "module",
    ownerDepartmentId: "demo-dept-2",
    ownerDepartmentName: "Phòng Tài chính",
    moduleStatusCode: "trained",
    moduleStatusLabel: "Đã tập huấn",
    classification: "Core",
    sortOrder: 5,
    issueTotal: 19,
    handedOver: 11,
    remaining: 8,
    progress: 58,
    detailCount: 5,
  },
];

const details: ContractDetailItem[] = [
  { id: "d1", parentId: null, contractItemId: "demo-module-1", code: "1", content: "Đăng ký học phần", nodeType: "module", level: 0, sortOrder: 1, note: null, hasChildren: true },
  { id: "d2", parentId: "d1", contractItemId: "demo-module-1", code: "1.1", content: "Cấu hình đợt đăng ký học phần", nodeType: "group", level: 1, sortOrder: 2, note: null, hasChildren: true },
  { id: "d3", parentId: "d2", contractItemId: "demo-module-1", code: "1.1.1", content: "Thiết lập thời gian mở/đóng đợt đăng ký", nodeType: "function", level: 2, sortOrder: 3, note: null, hasChildren: false },
  { id: "d4", parentId: "d2", contractItemId: "demo-module-1", code: "1.1.2", content: "Thiết lập đối tượng sinh viên được đăng ký", nodeType: "function", level: 2, sortOrder: 4, note: "Kiểm tra điều kiện khóa học", hasChildren: false },
  { id: "d5", parentId: "d1", contractItemId: "demo-module-1", code: "1.2", content: "Sinh viên thực hiện đăng ký", nodeType: "group", level: 1, sortOrder: 5, note: null, hasChildren: true },
  { id: "d6", parentId: "d5", contractItemId: "demo-module-1", code: "1.2.1", content: "Tra cứu danh sách lớp học phần", nodeType: "function", level: 2, sortOrder: 6, note: null, hasChildren: false },
  { id: "d7", parentId: "d5", contractItemId: "demo-module-1", code: "1.2.2", content: "Đăng ký / hủy đăng ký học phần", nodeType: "function", level: 2, sortOrder: 7, note: null, hasChildren: false },
  { id: "d8", parentId: null, contractItemId: "demo-module-2", code: "2", content: "Quản lý chương trình đào tạo", nodeType: "module", level: 0, sortOrder: 8, note: null, hasChildren: true },
  { id: "d9", parentId: "d8", contractItemId: "demo-module-2", code: "2.1", content: "Khai báo khung chương trình", nodeType: "group", level: 1, sortOrder: 9, note: null, hasChildren: true },
  { id: "d10", parentId: "d9", contractItemId: "demo-module-2", code: "2.1.1", content: "Thiết lập cấu trúc học kỳ và học phần", nodeType: "function", level: 2, sortOrder: 10, note: null, hasChildren: false },
  { id: "d11", parentId: null, contractItemId: "demo-module-3", code: "3", content: "Quản lý học phí", nodeType: "module", level: 0, sortOrder: 11, note: null, hasChildren: true },
  { id: "d12", parentId: "d11", contractItemId: "demo-module-3", code: "3.1", content: "Thiết lập biểu phí", nodeType: "group", level: 1, sortOrder: 12, note: null, hasChildren: true },
  { id: "d13", parentId: "d12", contractItemId: "demo-module-3", code: "3.1.1", content: "Khai báo đơn giá học phí theo chương trình", nodeType: "function", level: 2, sortOrder: 13, note: null, hasChildren: false },
];

export function createDemoContract(projectId: string): ContractData {
  return {
    source: "demo",
    generatedAt: new Date().toISOString(),
    projectId,
    role: "admin",
    canManage: true,
    summary: {
      items: overview.length,
      modules: overview.filter((item) => item.itemType === "module").length,
      subsystems: overview.filter((item) => item.itemType === "subsystem").length,
      details: details.length,
      issues: 65,
      handedOver: 46,
      remaining: 19,
      handoverProgress: 71,
      unmappedDetails: 0,
    },
    overview,
    details,
    filters: {
      departments: [
        { value: "demo-dept-1", label: "Phòng Đào tạo" },
        { value: "demo-dept-2", label: "Phòng Tài chính" },
      ],
      moduleStatuses: [
        { value: "surveyed", label: "Đã khảo sát" },
        { value: "ready_training", label: "Sẵn sàng tập huấn" },
        { value: "trained", label: "Đã tập huấn" },
      ],
    },
  };
}
